### ISSUE TITLE
Help explanation of peakshitf

### ISSUE THREAD

**Issue by gde061** [teleshoes/tpacpi-bat#71] opened 2016-10-13 01:52 UTC
Not really and issue, but just in case there is occasion down the road to tweak the help file text, it seems from [blog.lenovo.com/en/blog/peak-shift-with-power-manager](url)  that the peak shift flag is a setting that inhibits charge during "peak electricity rate" hours, i.e., daytime hours when demand for AC etc. overburdens the electric grid, and then reverts to charging during non-peak hours.  My reason for posting explanation is in case anyone else is confused and might probably come here as first point of investigation.

**Comment by teleshoes** [comment] 2016-10-13 04:28
yea, but what it ACTUALLY does is hard to pin down.
i havent looked into it in a long time so my memory's a bit fuzzy, but i believe that i came to the tentative conclusion that its just literally an exact duplicate of IC in function, and the reason that its separate is just to let userspace software (e.g.: ThinkVantage Power Manager) set and control both separately.

**Closed by teleshoes** 2016-10-13 04:28 UTC
